import { RadialEditorialCollection } from './types';

export const pneumaReferenceCollection: RadialEditorialCollection = {
  id: 'la-bonita-annular-2026',
  monogram: 'LB',
  year: '2026',
  collectionTitle: 'COLECCIÓN ORO 10K & 14K',
  tagline: 'Orfebrería Esculpida en Oro Puro • Piezas de Autor',
  contact: {
    phone: '+15025994250',
    displayPhone: '(502) 599-4250',
    email: 'SALES@LABONITAJEWELRY.COM',
    brandName: 'LA BONITA JEWELRY',
    locationLine1: 'BASED IN',
    locationLine2: '( LOUISVILLE, KENTUCKY )',
  },
  items: [
    {
      id: 'anillo-radiant-solitario',
      title: 'Anillo Radiant Solitario Oro 14K',
      category: 'Anillos',
      tag: 'Corte Radiant',
      purity: '14K',
      weight: '4.85g',
      price: 980,
      imageUrl: '/assets/product-anillo-signet.jpg',
      description: 'Gema central talla radiant engarzada en cuatro garras de perfil cónico sobre montura en oro macizo.',
    },
    {
      id: 'anillo-corazon-diamante',
      title: 'Solitario Corazón Romántico 14K',
      category: 'Compromiso',
      tag: 'Talla Corazón',
      purity: '14K',
      weight: '3.90g',
      price: 890,
      imageUrl: '/assets/product-aretes-profile.jpg',
      description: 'Zafiro o diamante central corte corazón con galería pulida al espejo y brazo redondeado confort.',
    },
    {
      id: 'anillo-geometrico-arquitectura',
      title: 'Anillo Doble Prisma Arquitectónico',
      category: 'Vanguardia',
      tag: 'Diseño Modernista',
      purity: '10K',
      weight: '5.75g',
      price: 620,
      imageUrl: '/assets/collection-anillos.jpg',
      description: 'Estructura angular tridimensional con líneas facetadas inspiradas en la orfebrería modernista.',
    },
    {
      id: 'cadena-curb-italiana',
      title: 'Cadena Italian Curb Sólido 10K',
      category: 'Cadenas',
      tag: 'Oro Sólido',
      purity: '10K',
      weight: '12.06g',
      price: 1380,
      imageUrl: '/assets/collection-cadenas.jpg',
      description: 'Eslabón cubano italiano de densidad continua, 24 pulgadas con broche de caja reforzado.',
    },
    {
      id: 'pulsera-clover-royal',
      title: 'Pulsera Trébol Royal Blue 14K',
      category: 'Pulseras',
      tag: 'Esmalte Real',
      purity: '14K',
      weight: '4.90g',
      price: 590,
      imageUrl: '/assets/product-pulseras-clover.jpg',
      description: 'Motivos de trébol en esmalte azul cobalto engastados en oro amarillo de 14 quilates.',
    },
    {
      id: 'manillas-bangle-duo',
      title: 'Manillas Bangle Dúo Rígidas 14K',
      category: 'Brazaletes',
      tag: 'Más Solicitada',
      purity: '14K',
      weight: '6.80g',
      price: 780,
      imageUrl: '/assets/product-pulseras-bangle.jpg',
      description: 'Brazaletes tubulares rígidos con cierre de bisagra oculta y acabado artesanal pulido.',
    },
  ],
};
